# Generated by Django 3.1.3 on 2021-04-29 00:20

import app.blog.models
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_status_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='post',
            name='fonte',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        # migrations.AlterField(
        #     model_name='post',
        #     name='image',
        #     field=models.ImageField(blank=True, null=True, upload_to=app.blog.models.name_image_post, verbose_name='Imagem'),
        # ),
        migrations.AlterField(
            model_name='post',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SubTítulo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Texto'),
        ),
    ]
