# Generated by Django 3.1.3 on 2021-05-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210429_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dt_publicado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Publicado em'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(help_text='Entre com o seu endereço de email válido!', max_length=120),
        ),
    ]
