# Generated by Django 3.1.3 on 2021-02-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default=None, max_length=120),
        ),
        migrations.AddField(
            model_name='post',
            name='fonte',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
